apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ include "wiremock.name" . }}
    helm.sh/chart: {{ include "wiremock.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  path: {{ .Values.ingress.path }}
  port:
    targetPort: {{ include "wiremock.fullname" . }}
  to:
    kind: Service
    name: {{ include "wiremock.fullname" . }}
    weight: 100
  wildcardPolicy: None

