{{- if eq .Values.global.deploymentMode "development" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wiremock.volume.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wiremock.volume.size }}
  storageClassName: {{ .Values.global.storageClass }}
  volumeMode: Filesystem
{{- end }}
